version: 2.1
orbs:
  docker: circleci/docker@0.2.0
jobs:
  build_with_gradle:
    docker:
      - image: circleci/openjdk:11
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Gradle build
          command: |
            ./gradlew --parallel docker sonarqube \
            -Dsonar.projectKey=clouditor_clouditor \
            -Dsonar.organization=clouditor \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=$SONAR_TOKEN
      - docker/check
      - docker/push:
          image: clouditor/engine
          tag: latest
      - docker/push:
          image: clouditor/ui
          tag: latest
      - docker/push:
          image: clouditor/clouditor
          tag: latest          
workflows:
  build_with_gradle:
    jobs:
      - build_with_gradle:
          context: org-global
